### ISSUE TITLE
rosdep integration

### ISSUE THREAD

**Issue by wixiw** [ifm/ifm3d-ros#18]
I tried to compile the ROS ifm driver for O3D cameras in my ROS workspace. I have an error:
/usr/include/ifm3d/fg/detail/byte_buffer.hpp:21:26: fatal error: glog/logging.h: No such file or directory

Fix seems straight forward : "glog" os dependency is not met. The author of the following page:
https://github.com/ifm/ifm3d-ros/blob/master/doc/building.md 
expect the user to have read this:
https://github.com/ifm/ifm3d-ros/blob/master/doc/kinetic.md
Especially: sudo apt-get install libgoogle-glog-dev

In the ROS world, we expect the rosdep tool to do the job without having to bother. For instance, in my workspace provided by a team member I usually run before anything else:
rosdep install --from-paths src --ignore-src -r -y
In this case it shows me:
#All required rosdeps installed successfully

It seems that rosdep doesn't have any reference to your dependencies :
```
rosdep resolve google-glog
ERROR: no rosdep rule for 'google-glog'
rosdep resolve xmlrpc-c++8
ERROR: no rosdep rule for 'xmlrpc-c++8'
```
You should have a deeper look as I just made a quick guess, and worry about why you are the first to use those depencies, as ROS is used by a lot of people and it would be surprising you are the first needing glog and xmlrpc, so I might have missed the right spelling.

If required, you can ask for your dependencies to be added as stated here : 
http://docs.ros.org/independent/api/rosdep/html/contributing_rules.html  

Version : I'm on a Ubunty 16.04 / ROS kinetic

**Comment by graugans** [comment]
Hey @wixiw could you please translate the above to English please. Maybe @Arag24 can assist you

**Comment by Arag24** [comment]
Hi @wixiw , @graugans ,
Question below is related to inclusion of libraries source when building `ifm3d-ros`.

@wixiw could see from [https://github.com/ifm/ifm3d-ros/blob/master/doc/kinetic.md](https://github.com/ifm/ifm3d-ros/blob/master/doc/kinetic.md)
it's mandatory to include :

> $ sudo apt-get install libxmlrpc-c++8-dev
$ sudo apt-get install libgoogle-glog-dev

However, as he was using `rosdep` command, and the answer was

>  #All required rosdeps installed successfully

I'm pretty sure he spent some time to find what dependency he has to includewith, is that true @wixiw?


Open topic is the following : 
As there is no `ERROR: no rosdep rule for 'google-glog'`, @wixiw is asking if rules can be added directly from here [(http://docs.ros.org/independent/api/rosdep/html/contributing_rules.html)](http://docs.ros.org/independent/api/rosdep/html/contributing_rules.html).
In such way, `ifm3d-ros` would be more efficient, having dependecy included without having deep look inside ifm repo, and only check with command as 

> rosdep install --from-paths src --ignore-src -r -y
to see if eveything is running correctly ? (as apparently many should do in ROS environment)

Does it make sense, @graugans , @wixiw  ?

**Comment by wixiw** [comment]
I translated the question. @Arag24 perfect translation of the need.

Note that I (obviously) have a workaround from the "apt-get" commands, I just send the request for your continuous improvment.

**Comment by theseankelly** [comment]
This work is now being tracked by #30 -- 'submit ifm3d to the ROS package index'
