### ISSUE TITLE
Error in catkin_make

### ISSUE THREAD

**Issue by matteofiorini** [ifm/ifm3d-ros#20]
Hi, 
I am having issues about the installation. I have ros Kinetic and ubuntu 16.04. I followed the whole procedure but in the last command I get this error:

matteo@matteo-MS-7A37:~/catkin_ws/ifm3d$ catkin_make run_tests
Base path: /home/matteo/catkin_ws/ifm3d
Source space: /home/matteo/catkin_ws/ifm3d/src
Build space: /home/matteo/catkin_ws/ifm3d/build
Devel space: /home/matteo/catkin_ws/ifm3d/devel
Install space: /home/matteo/catkin_ws/ifm3d/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/matteo/catkin_ws/ifm3d/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/kinetic
-- This workspace overlays: /opt/ros/kinetic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/matteo/catkin_ws/ifm3d/build/test_results
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.18
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- Configuring done
-- Generating done
-- Build files have been written to: /home/matteo/catkin_ws/ifm3d/build
####
####
Scanning dependencies of target run_tests
Built target run_tests
matteo@matteo-MS-7A37:~/catkin_ws/ifm3d$ catkin_make -DCMAKE_INSTALL_PREFIX=${LPR_ROS}/ifm3d install
Base path: /home/matteo/catkin_ws/ifm3d
Source space: /home/matteo/catkin_ws/ifm3d/src
Build space: /home/matteo/catkin_ws/ifm3d/build
Devel space: /home/matteo/catkin_ws/ifm3d/devel
Install space: /ifm3d
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/matteo/catkin_ws/ifm3d/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/kinetic
-- This workspace overlays: /opt/ros/kinetic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/matteo/catkin_ws/ifm3d/build/test_results
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.18
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- Configuring done
-- Generating done
-- Build files have been written to: /home/matteo/catkin_ws/ifm3d/build
####
####
Install the project...
-- Install configuration: ""
CMake Error at cmake_install.cmake:38 (file):
  file problem creating directory: /ifm3d

Makefile:61: set di istruzioni per l'obiettivo "install" non riuscito
make: *** [install] Errore 1
Invoking "make install -j8 -l8" failed

Can someone please help me?
Thank you so much.

**Comment by tpanzarella** [comment]
It looks like you are trying to install in `/ifm3d` which you likely do not have permission to do. Did you specify `-DCMAKE_INSTALL_PREFIX=...` to a directly where you do have permission? I'd suggest you re-look at [these instructions](https://github.com/ifm/ifm3d-ros/blob/master/doc/building.md) and make sure you did not omit anything.
