### ISSUE TITLE
03M 950 & 03M 151

### ISSUE THREAD

**Issue by saberclaw1213** [ifm/ifm3d-ros#22]
Does ifm3d-ros supports this model? Thanks in advance

**Comment by tpanzarella** [comment]
No. It does not.

**Comment by pfrydlewicz** [comment]
hi @saberclaw1213 ,
you might have a look at this repo:
http://wiki.ros.org/ifm_o3mxxx

However the supported firmware is not up to date.
I did a fork some time ago and added support for the newest interface of the DI firmware.
Here: https://github.com/pfrydlewicz/ifm_o3mxxx

Hope it helps.
Paul
