### ISSUE TITLE
O3X120AB, Firmware version 2.0.10412. What is the ifm3d version and ifm3d-ros version should I use?

### ISSUE THREAD

**Issue by coa06yl** [ifm/ifm3d-ros#73]
O3X120AB, Firmware version 2.0.10412. What is the ifm3d version and ifm3d-ros version should I use? Thanks!

**Comment by lola-masson** [comment]
@coa06yl see answer in https://github.com/ifm/ifm3d-ros/discussions/71#discussioncomment-6001387
